export enum ReduxType {
  // Navigation
  AUTH = 'AUTH',
  MAIN = 'MAIN',
  SPLASH = 'SPLASH',
  ERROR = 'ERROR',
  STOP_LOADING = 'STOP_LOADING',
  START_LOADING = 'START_LOADING',

  // Respons
  GET_ORDERS = 'GET_ORDERS',
  GET_ORDERS_DETAILS = 'GET_ORDERS_DETAILS',
  GET_ME = 'GET_ME',
}
