export enum ReduxType {
  // Navigation
  AUTH = 'AUTH',
  MAIN = 'MAIN',
  SPLASH = 'SPLASH',
  ERROR = 'ERROR',
  STOP_LOADING = 'STOP_LOADING',
  START_LOADING = 'START_LOADING',

  GET_PROFILE = 'GET_PROFILE',

  // Respons
  GET_ORDERS = 'GET_ORDERS',
  SAVE_PUBLICATION_URL = 'SAVE_PUBLICATION_URL',
  SAVE_QUILL_SOLUTION = 'SAVE_QUILL_SOLUTION',
  SAVE_QUILL_TASK = 'SAVE_QUILL_TASK',
  GET_ORDERS_DETAILS = 'GET_ORDERS_DETAILS',
  GET_ME = 'GET_ME',
  GET_BALANCE = 'GET_BALANCE',
  GET_PROVIDERS = 'GET_PROVIDERS',
}
